#!/bin/bash

hostname="test"
vg="amdahl-vg"

vm_boot_volume="vm-$hostname-boot"
vm_lvm_volume="vm-$hostname-lvm"
vm_pv="/dev/$vg/$vm_lvm_volume"
vm_vg="$hostname-vg"

if [[ ! $EUID -eq 0 ]]; then
    echo "You must be root to run this utility."
    exit 1
fi

lv_exists() {
    if lvs --noheadings --separator=',' --select="lv_name=$1" | cut -f1 -d',' | grep "$1" >/dev/null; then
        return 0
    else
        return 1
    fi
}

if lv_exists $vm_boot_volume; then
    echo "There is already a boot LV for \`$hostname'."
    exit 1
fi

echo "*** Creating VM filesystems for \`$hostname'..."
echo "*** Creating /boot... "
if lvcreate -L256M -n "$vm_boot_volume" "/dev/$vg"; then
    if mkfs -t ext4 "/dev/$vg/$vm_boot_volume"; then
        echo "*** /boot created successfully."
    else
        echo "*** Couldn't mkfs /boot :("
        exit 1
    fi
else
    echo "*** Couldn't lvcreate /boot :("
    exit 1
fi    
echo "*** Creating LVM volume group \`$hostname-vg'..."

if lvcreate -L100M -n "$vm_lvm_volume" "/dev/$vg"; then
    if pvcreate "/dev/$vg/$vm_lvm_volume"; then
        if vgcreate "$vm_vg" "$vm_pv"; then
            if lvcreate -L50M -n root "$vm_vg"; then
                echo "made root lv"
            fi
        fi
    fi
fi
